apiVersion: v1
kind: ConfigMap
metadata:
  name: dockmaster-config
  namespace: dockmaster
data:
  BACKEND_PORT: "8081"
  FRONTEND_PORT: "3000"
  LOG_LEVEL: "info"
  DB_PATH: "/app/data/dockmaster.db"
  FRONTEND_URL: "http://dockmaster-frontend:3000"
---
apiVersion: v1
kind: Secret
metadata:
  name: dockmaster-secrets
  namespace: dockmaster
type: Opaque
stringData:
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "admin123"
